### ISSUE TITLE
Level Buddy Update

### ISSUE THREAD

**Issue by JusKillmeQik** [Pastillage/PoE_Level_Buddy#6]
Hey, I saw on Reddit that you're planning on updating this.

I recently wrote something very similar that uses Autohotkey instead of java. I understand if you just want to work on your own thing, but if you'd like to contribute to the project I started I'd be happy to work with you. I've already implemented a few of the future features you have planned and I'd be really excited to figure out how to do PoB importing.

If you're not interested, no hard feelings. But if you are, check it out here: https://github.com/JusKillmeQik/LevelingGuide

**Comment by POE-Addon-Launcher** [comment]
Unfortunately I have no AHK knowledge, nor desire to learn AHK, so while it would be great to work together, I'm gonna have to decline your offer.

**Comment by JusKillmeQik** [comment]
Thanks for the response. I'm excited to see where your project and Path of Leveling go. I'm going to continue developing my script until I see somewhere else I can help. Cheers!
