### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by TheOne320** [Pastillage/PoE_Level_Buddy#7]
When I double click the .jar file nothing happens. Is there a log created somewhere to help be debug?

**Comment by POE-Addon-Launcher** [comment]
Get the latest version

**Comment by TheOne320** [comment]
I am using version 1.2.1.

**Comment by POE-Addon-Launcher** [comment]
Please, run it from a cmd window and provide me with the ouput

java -jar PoE_Level_Buddy_v1.2.1.jar

**Comment by TheOne320** [comment]
Weirdly it is now working. I will start it via cmd every time now and if it happens again I will post the log here.
