### ISSUE TITLE
Not changing with client.txt

### ISSUE THREAD

**Issue by ohlawdie** [Pastillage/PoE_Level_Buddy#8]
Hey @Pastillage, unfortunately I am having issues with your add-on. I am running JRE 8 (update 211) and while I can get the .jar file to execute without having to do anything on the command line I do not see any change in behavior in accordance with the client.txt. Any help would be much obliged, thanks!

**Comment by POE-Addon-Launcher** [comment]
Are you sure you pointed it to the right client.txt?
